sudo: required

language: php

php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
  - master

before_install:
  - travis_retry composer self-update

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --no-suggest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    recipients:
      - info@miladrahimi.com
    on_success: change
    on_failure: always
